Fix bugs around creating ECDAA key
google/go-tpm pull request #285
Opened 2022-06-14 07:16 UTC by akakou

There are the following bugs around creating ECDAA key:

-   CurveBNP256 number is wrong
    -  TPM expects `0x10` to TPM2_ECC_BN_P256 but this library does not set so.
-  ECDAA `count` size is wrong
    -  TPM expects 16bit but, actually 32bit in go-tpm.

So this PR fixes these bugs.

### Reference

- https://trustedcomputinggroup.org/wp-content/uploads/TSS_Overview_Common_Structures_Version-0.9_Revision-03_Review_030918.pdf

2022-06-27 21:36 UTC, chrisfenner requested changes
This change looks good, only a small fix for CurveBNP638.

BTW, we are doing a major refactor to the API in https://github.com/google/go-tpm/tree/tpmdirect - have you thought about how ECDAA could be exposed via the legacy command model, or do you want to build this in TPMDirect?

2022-06-28 07:02 UTC, akakou commented on tpm2/constants.go
>  	CurveBNP638
Did you mean the `CurveBNP638`?

2022-06-28 07:02 UTC, akakou commented on tpm2/constants.go
>  	CurveBNP638
@chrisfenner

2022-06-28 10:16 UTC, akakou commented on tpm2/constants.go
>  	CurveBNP638
I replaced them on a new commit!

2022-06-28 10:43 UTC, akakou commented
Umm...I think we have to implement some TPM commands(e.g. TPM2_Commit) first to run ECDAA. (I made this Issue #287)
Now I'm trying to implement `TPM2_Commit` to the `tpmdirect` branch.

But I don't think that I develop ECDAA API (e.g. ECDAA_JOIN) directly, because there is some process that should not be in the scope of the TPM.
(FIDO ECDAA defines the other module running on a client named ASM. There are some processes for ECDAA running on ASM, not on TPM)

https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html#ecdaa-sign-split-between-tpm-and-asm

2022-06-28 14:05 UTC, chrisfenner commented
Sounds good. Do you want to send a PR to the `tpmdirect` branch instead of `master`?

2022-06-29 05:40 UTC, akakou commented
You are right! I will change the destination branch to `tpmdirect`.

2022-06-29 05:41 UTC, akakou commented
But I am concerned that the master branch remains wrong about BN256 and ECDAA.
Because some people using BN256 or ECDAA with master branch may be confused.

I would like to confirm just in case; the tpmdirect branch will be merged with the master branch finally, right?

2022-09-05 07:33 UTC, akakou commented
This discussion was solved because we decided that contribute to `tpmdirect`.
So I close this PR.

2022-09-05 07:33 UTC, closed without merging